name: Update README with Recent Activity

on:
  schedule:
    - cron: '0 0 * * *'  # menjalankan setiap hari pada pukul 00:00 UTC
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Configure Git
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Check Git Status
        id: git-status
        run: echo ::set-output name=changes::$(git status --porcelain)

      - name: Commit and Push Changes
        if: steps.git-status.outputs.changes
        run: |
          git add README.md
          git commit -m "Update last activity in README"
          git push
