name: Update README with Recent Activity

on:
  schedule:
    - cron: '0 * * * *'  # menjalankan setiap jam
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Update README
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python update_readme.py

      - name: Commit changes if there are any
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          if [[ `git status --porcelain` ]]; then
            git add README.md
            git commit -m "Update last activity in README"
            git push
          else
            echo "No changes detected"
