name: Update README with Recent Activity

on:
  schedule:
    - cron: '0 0 * * *'  # menjalankan setiap hari pada pukul 00:00 UTC
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Ganti dengan versi Python yang diinginkan

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Configure Git
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Update README
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: python update_readme.py

      - name: Commit changes if there are any
        run: |
          if [[ $(git status --porcelain) ]]; then
            git add README.md
            git commit -m "Update last activity in README"
            git push
          else
            echo "No changes detected"
